# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98bd7e7cd934ebe6650ed42b849a7e869690c4d256902f425859d4a2b6589a5fd266ba5de966a4d614af92a9c1556d770c09ba901a277b0d764a010b5bddea78

test:
  secret_key_base: 7372ac77d99a7327d90dccefce8844c9d35cb0dfb0dd22b2084f77ee2a29c126dd2107237390b0aef4a95d1c9e414769ef943b05f476ed97172f60912803b75d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
